[package]
name = "groupbot"
version = "0.1.0"
authors = ["quininer kel <quininer@live.com>"]

[dependencies]
chrono = "0.2"
toml = "0.1"
rustc-serialize = "0.3"

[dependencies.tox]
git = "https://github.com/quininer/tox-rs.git"
